#!/usr/bin/env bash
# 07 - Build free software packages + pacman repo for GitHub Pages.
# Runs INSIDE the LFS chroot, after chroot/06-xorg-xfce.sh.
#
# Builds Yaru theme from source and imports fcitx5 from Arch prebuilt,
# producing pacman packages + source archives + repo-add database in
# /mnt/lfs/pkgrepo/.  These are NOT installed into the live system root;
# they are published to GitHub Pages for user-side pacman -S installation.
#
# Single-package failures are logged as warnings but do NOT abort the script.
set -euo pipefail

export SOURCES=/sources
export SCRIPTS_DIR=/build
export STAGES_DIR=/build/stages
export CONFIG_DIR=/config
source /build/env.sh
source /build/common.sh

[ "$(uname -m)" = "x86_64" ] || die "packages: x86_64 only"
command -v curl >/dev/null    || die "packages: curl missing"
command -v python3 >/dev/null || die "packages: python3 missing"
command -v meson >/dev/null   || die "packages: meson missing (extras must run first)"
command -v ninja >/dev/null   || die "packages: ninja missing"
command -v repo-add >/dev/null || die "packages: repo-add missing (pacman build must run first)"

REPO_DIR=/mnt/lfs/pkgrepo
STAGING=/tmp/pkgbuild
rm -rf "$STAGING" "$REPO_DIR"
mkdir -p "$REPO_DIR" "$STAGING"/{yaru,src}

DL=/root/downloads
[ -d "$DL" ] || die "packages: $DL not found (host must pre-download sources)"

# =====================================================================
# Helper: build a pacman package from a staging tree
# pkg_stage <name> <version> <description> <file1> [file2 ...]
#   Creates <name>-<version>-1-x86_64.pkg.tar.zst in $REPO_DIR
# =====================================================================
pkg_stage() {
    local name="$1" ver="$2" desc="$3"
    shift 3
    local stage="$STAGING/$name"
    rm -rf "$stage"
    mkdir -p "$stage"

    local p f dest
    for p in "$@"; do
        for f in $p; do
            if [ -e "$f" ]; then
                dest="$stage$f"
                mkdir -p "$(dirname "$dest")"
                cp -al "$f" "$dest" 2>/dev/null || cp -a "$f" "$dest"
            fi
        done
    done

    # PKGINFO
    cat > "$stage/.PKGINFO" << PKGEOF
# Generated by LFS-CN packages build
pkgname = $name
pkgver = $ver-1
pkgdesc = $desc
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = custom
PKGEOF

    local archive="$REPO_DIR/$name-$ver-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage"
    log "  package: $name-$ver-1-x86_64.pkg.tar.zst"
}

# =====================================================================
# Helper: create source tarball from a directory
# src_tarball <name> <ver> <src_dir>
# =====================================================================
src_tarball() {
    local name="$1" ver="$2" src_dir="$3"
    local out="$STAGING/src/${name}-${ver}.src.tar.gz"
    tar czf "$out" -C "$(dirname "$src_dir")" "$(basename "$src_dir")" 2>/dev/null || \
        tar czf "$out" -C "$STAGING/src" "$(basename "$src_dir")"
    log "  source: ${name}-${ver}.src.tar.gz"
}

# =====================================================================
# Package 1: Yaru theme (built from source)
# =====================================================================
log '==> building Yaru theme'
build_yaru() {
    local tarball="$DL/$YARU_TARBALL"
    if [ ! -f "$tarball" ]; then
        warn "Yaru tarball not found: $tarball — skipping"
        return 0
    fi

    local yaru_src="$STAGING/yaru-src"
    rm -rf "$yaru_src"
    mkdir -p "$yaru_src"
    tar xf "$tarball" -C "$yaru_src" --strip-components=1

    local build_dir="$STAGING/yaru/build"
    mkdir -p "$build_dir"

    # Build only GTK themes + icons + cursor + shell; skip sound,
    # gnome-shell old versions, docs, gettext, and tests.
    cd "$yaru_src"
    meson setup "$build_dir" \
        --prefix=/usr \
        --libdir=lib \
        -Dgnome_shell_40=false \
        -Dgnome_shell_41=false \
        -Dgnome_shell_42=false \
        -Dgnome_shell_43=false \
        -Dgnome_shell_44=false \
        -Dgnome_shell_45=false \
        -Dgnome_shell_46=false \
        -Dgnome_shell_47=false \
        -Dgnome_shell_48=false \
        -Dgnome_shell_49=true \
        -Dgnome_shell_50=true \
        -Dsounds=false \
        -Dicons=false \
        -Dcursor=true \
        -Dgtk=true \
        -Dsession=false \
        -Dwallpapers=false \
        -Dtests=false \
        -Ddocs=false \
        || { warn "Yaru meson setup failed"; return 0; }

    ninja -C "$build_dir" || { warn "Yaru ninja failed"; return 0; }

    # Install to staging prefix (NOT /)
    local prefix="$STAGING/yaru/prefix"
    DESTDIR="$prefix" ninja -C "$build_dir" install || { warn "Yaru install failed"; return 0; }

    # Package the installed files
    local files=()
    while IFS= read -r -d '' f; do
        files+=("$f")
    done < <(find "$prefix" -mindepth 1 -printf '%P\0' 2>/dev/null)

    if [ ${#files[@]} -gt 0 ]; then
        # Create the pacman package from the prefix tree
        local stage="$STAGING/yaru-pkg"
        rm -rf "$stage"
        mkdir -p "$stage"
        cp -a "$prefix"/. "$stage/"

        # PKGINFO
        cat > "$stage/.PKGINFO" << PKGEOF
pkgname = yaru-theme
pkgver = ${YARU_VER%%u*}-1
pkgdesc = Ubuntu Yaru theme (GTK2/GTK3/GTK4/icons/cursor/shell)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = CC-BY-SA-4.0
PKGEOF

        local archive="$REPO_DIR/yaru-theme-${YARU_VER%%u*}-1-x86_64.pkg.tar.zst"
        (
            cd "$stage"
            : > "/tmp/pkgfiles.$$"
            printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
            find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
            tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
            rm -f "/tmp/pkgfiles.$$"
        )
        rm -rf "$stage"
        log "  package: yaru-theme-${YARU_VER%%u*}-1-x86_64.pkg.tar.zst"
    else
        warn "Yaru: no files installed, skipping package"
    fi

    # Source tarball
    src_tarball "yaru" "${YARU_VER%%u*}" "$yaru_src"

    rm -rf "$yaru_src" "$build_dir" "$STAGING/yaru"
    log "  Yaru theme built and packaged"
}
build_yaru || warn "Yaru theme build failed (continuing)"

# =====================================================================
# Package 2-4: fcitx5 stack from Arch prebuilt
# =====================================================================
log '==> importing fcitx5 packages from Arch'
import_fcitx5() {
    local work="/tmp/fcitx5-import"
    rm -rf "$work"
    mkdir -p "$work/db"

    # Download Arch repo databases
    log "  downloading Arch repo databases"
    for repo in core extra; do
        local got=0
        for m in $ARCH_MIRRORS; do
            if curl -kfSL --retry 2 --max-time 120 -o "$work/db/$repo.db" \
                    "$m/$repo/os/x86_64/$repo.db" 2>/dev/null && [ -s "$work/db/$repo.db" ]; then
                got=1
                break
            fi
        done
        [ "$got" -eq 1 ] || { warn "Cannot download $repo.db — skipping fcitx5"; return 0; }
    done

    # Resolve dependency closure
    log "  resolving fcitx5 dependency closure"
    python3 "$SCRIPTS_DIR/chroot/arch-resolve-fcitx5.py" "$work/db" "$work" \
        > "$work/resolve.log" 2>&1 || {
        cat "$work/resolve.log" >&2
        warn "fcitx5 resolver failed — skipping"
        return 0
    }
    cat "$work/summary.txt"
    grep '^WARN' "$work/resolve.log" || true

    local total
    total=$(wc -l < "$work/dl.txt")
    [ "$total" -gt 0 ] || { warn "fcitx5 resolver produced empty list"; return 0; }
    log "  fcitx5 closure: $total packages to import"

    # Download packages into the repo directory (NOT extracting into /)
    local n=0
    while read -r repo filename; do
        [ -n "$filename" ] || continue
        n=$((n + 1))
        local got=0
        for m in $ARCH_MIRRORS; do
            if curl -kfSL --retry 2 --max-time 300 -o "$REPO_DIR/$filename" \
                    "$m/$repo/os/x86_64/$filename" 2>/dev/null && [ -s "$REPO_DIR/$filename" ]; then
                got=1
                break
            fi
        done
        [ "$got" -eq 1 ] || warn "  download failed: $repo/$filename"
        [ $((n % 20)) -eq 0 ] && log "    $n/$total done"
    done < "$work/dl.txt"
    log "  imported $n fcitx5 packages into pkgrepo"

    rm -rf "$work"
}
import_fcitx5 || warn "fcitx5 import failed (continuing)"

# =====================================================================
# Generate pacman repository database
# =====================================================================
log '==> generating pacman repository database'
cd "$REPO_DIR"

# Collect all .pkg.tar.zst files (including any from Arch import)
pkg_files=(*.pkg.tar.zst)
if [ -e "${pkg_files[0]}" ]; then
    repo-add lfscn.db.tar.gz "${pkg_files[@]}" || {
        warn "repo-add failed, retrying verbose"
        repo-add lfscn.db.tar.gz "${pkg_files[@]}"
    }
    ln -sfv lfscn.db.tar.gz lfscn.db
    log "  lfscn.db created with ${#pkg_files[@]} packages"
else
    warn "no packages found in $REPO_DIR"
fi

# =====================================================================
# Summary
# =====================================================================
log '==> package repo contents:'
ls -lh "$REPO_DIR"/ 2>/dev/null || true
log '==> packages build complete'
