#!/usr/bin/env bash
# 07 - Build free software packages + pacman repo for GitHub Pages.
# Runs INSIDE the LFS chroot, after chroot/05-extras.sh.
#
# Builds Yaru theme from source and imports fcitx5 from Arch prebuilt,
# producing pacman packages + source archives + repo-add database in
# /pkgrepo (host view: $LFS_ROOT/pkgrepo).  These are NOT installed into
# the live system root; they are published to GitHub Pages for user-side
# pacman -S installation.
#
# Single-package failures are logged as warnings but do NOT abort the script.
set -euo pipefail

export SOURCES=/sources
export SCRIPTS_DIR=/build
export STAGES_DIR=/build/stages
export CONFIG_DIR=/config
source /build/env.sh
source /build/common.sh

[ "$(uname -m)" = "x86_64" ] || die "packages: x86_64 only"
command -v curl >/dev/null    || die "packages: curl missing"
command -v python3 >/dev/null || die "packages: python3 missing"
command -v meson >/dev/null   || die "packages: meson missing (extras must run first)"
command -v ninja >/dev/null   || die "packages: ninja missing"
command -v repo-add >/dev/null || die "packages: repo-add missing (pacman build must run first)"

# NOTE: this script runs inside the chroot whose root IS $LFS_ROOT on the
# host, so /pkgrepo here == host /mnt/lfs/pkgrepo. Never write /mnt/lfs/...
# from inside the chroot (that would nest under /mnt/lfs/mnt/lfs).
REPO_DIR=/pkgrepo
STAGING=/tmp/pkgbuild
rm -rf "$STAGING" "$REPO_DIR"
mkdir -p "$REPO_DIR" "$STAGING"/{yaru,src}

DL=/root/downloads
[ -d "$DL" ] || die "packages: $DL not found (host must pre-download sources)"

# =====================================================================
# Helper: build a pacman package from a staging tree
# pkg_stage <name> <version> <description> <file1> [file2 ...]
#   Creates <name>-<version>-1-x86_64.pkg.tar.zst in $REPO_DIR
# =====================================================================
pkg_stage() {
    local name="$1" ver="$2" desc="$3"
    shift 3
    local stage="$STAGING/$name"
    rm -rf "$stage"
    mkdir -p "$stage"

    local p f dest
    for p in "$@"; do
        for f in $p; do
            if [ -e "$f" ]; then
                dest="$stage$f"
                mkdir -p "$(dirname "$dest")"
                cp -al "$f" "$dest" 2>/dev/null || cp -a "$f" "$dest"
            fi
        done
    done

    # PKGINFO
    cat > "$stage/.PKGINFO" << PKGEOF
# Generated by LFS-CN packages build
pkgname = $name
pkgver = $ver-1
pkgdesc = $desc
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = custom
PKGEOF

    local archive="$REPO_DIR/$name-$ver-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage"
    log "  package: $name-$ver-1-x86_64.pkg.tar.zst"
}

# =====================================================================
# Helper: create source tarball from a directory
# src_tarball <name> <ver> <src_dir>
# =====================================================================
src_tarball() {
    local name="$1" ver="$2" src_dir="$3"
    local out="$STAGING/src/${name}-${ver}.src.tar.gz"
    tar czf "$out" -C "$(dirname "$src_dir")" "$(basename "$src_dir")" 2>/dev/null || \
        tar czf "$out" -C "$STAGING/src" "$(basename "$src_dir")"
    log "  source: ${name}-${ver}.src.tar.gz"
}

# =====================================================================
# Package 1: Yaru theme (built from source)
# =====================================================================
log '==> building Yaru theme'

# sassc: Yaru's meson.build hard-requires the program (root cause #57).
# Official plain-Makefile build, no autotools needed.
build_sassc() {
    command -v sassc >/dev/null 2>&1 && return 0
    local ls="$DL/libsass-$LIBSASS_VER.tar.gz" sc="$DL/sassc-$SASSC_VER.tar.gz"
    if [ ! -f "$ls" ] || [ ! -f "$sc" ]; then
        warn "sassc/libsass tarballs missing - Yaru will fail to configure"
        return 0
    fi
    rm -rf /tmp/libsass /tmp/sassc-src
    mkdir -p /tmp/libsass /tmp/sassc-src
    tar xf "$ls" -C /tmp/libsass --strip-components=1
    tar xf "$sc" -C /tmp/sassc-src --strip-components=1
    export SASS_LIBSASS_PATH=/tmp/libsass
    make -C /tmp/libsass -j"$NPROC" || warn "libsass build failed"
    make -C /tmp/sassc-src -j"$NPROC" || warn "sassc build failed"
    make -C /tmp/libsass install PREFIX=/usr >/dev/null || warn "libsass install failed"
    make -C /tmp/sassc-src install PREFIX=/usr >/dev/null || warn "sassc install failed"
    ldconfig
}
build_sassc

build_yaru() {
    local tarball="$DL/$YARU_TARBALL"
    if [ ! -f "$tarball" ]; then
        warn "Yaru tarball not found: $tarball — skipping"
        return 0
    fi
    command -v sassc >/dev/null 2>&1 \
        || die "packages: sassc unavailable but Yaru requires it"

    local yaru_src="$STAGING/yaru-src"
    rm -rf "$yaru_src"
    mkdir -p "$yaru_src"
    tar xf "$tarball" -C "$yaru_src" --strip-components=1

    local build_dir="$STAGING/yaru/build"
    mkdir -p "$build_dir"

    # Build only GTK themes + icons + cursor + shell; skip sound,
    # gnome-shell old versions, docs, gettext, and tests.
    cd "$yaru_src"
    meson setup "$build_dir" \
        --prefix=/usr \
        --libdir=lib \
        -Dgnome-shell=false \
        -Dsounds=false \
        -Dicons=true \
        -Dgtk=true \
        -Dsessions=false \
        -Dgtksourceview=false \
        -Dmetacity=false \
        || { warn "Yaru meson setup failed"; return 0; }

    ninja -C "$build_dir" || { warn "Yaru ninja failed"; return 0; }

    # Install to staging prefix (NOT /)
    local prefix="$STAGING/yaru/prefix"
    DESTDIR="$prefix" ninja -C "$build_dir" install || { warn "Yaru install failed"; return 0; }

    # Package the installed files
    local files=()
    while IFS= read -r -d '' f; do
        files+=("$f")
    done < <(find "$prefix" -mindepth 1 -printf '%P\0' 2>/dev/null)

    if [ ${#files[@]} -gt 0 ]; then
        # Create the pacman package from the prefix tree
        local stage="$STAGING/yaru-pkg"
        rm -rf "$stage"
        mkdir -p "$stage"
        cp -a "$prefix"/. "$stage/"

        # PKGINFO
        cat > "$stage/.PKGINFO" << PKGEOF
pkgname = yaru-theme
pkgver = ${YARU_VER%%u*}-1
pkgdesc = Ubuntu Yaru theme (GTK2/GTK3/GTK4/icons/cursor/shell)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = CC-BY-SA-4.0
PKGEOF

        local archive="$REPO_DIR/yaru-theme-${YARU_VER%%u*}-1-x86_64.pkg.tar.zst"
        (
            cd "$stage"
            : > "/tmp/pkgfiles.$$"
            printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
            find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
            tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
            rm -f "/tmp/pkgfiles.$$"
        )
        rm -rf "$stage"
        log "  package: yaru-theme-${YARU_VER%%u*}-1-x86_64.pkg.tar.zst"
    else
        warn "Yaru: no files installed, skipping package"
    fi

    # Source tarball
    src_tarball "yaru" "${YARU_VER%%u*}" "$yaru_src"

    rm -rf "$yaru_src" "$build_dir" "$STAGING/yaru"
    log "  Yaru theme built and packaged"
}
build_yaru || warn "Yaru theme build failed (continuing)"

# =====================================================================
# Package 2-4: fcitx5 stack from Arch prebuilt
# =====================================================================
log '==> importing fcitx5 packages from Arch'
import_fcitx5() {
    local work="/tmp/fcitx5-import"
    rm -rf "$work"
    mkdir -p "$work/db"

    # Download Arch repo databases
    log "  downloading Arch repo databases"
    for repo in core extra; do
        local got=0
        for m in $ARCH_MIRRORS; do
            if curl -kfSL --retry 2 --max-time 120 -o "$work/db/$repo.db" \
                    "$m/$repo/os/x86_64/$repo.db" 2>/dev/null && [ -s "$work/db/$repo.db" ]; then
                got=1
                break
            fi
        done
        [ "$got" -eq 1 ] || { warn "Cannot download $repo.db — skipping fcitx5"; return 0; }
    done

    # Resolve dependency closure
    log "  resolving fcitx5 dependency closure"
    python3 "$SCRIPTS_DIR/chroot/arch-resolve-fcitx5.py" "$work/db" "$work" "" \
        > "$work/resolve.log" 2>&1 || {
        cat "$work/resolve.log" >&2
        warn "fcitx5 resolver failed — skipping"
        return 0
    }
    cat "$work/summary.txt"
    grep '^WARN' "$work/resolve.log" || true

    local total
    total=$(wc -l < "$work/dl.txt")
    [ "$total" -gt 0 ] || { warn "fcitx5 resolver produced empty list"; return 0; }
    log "  fcitx5 closure: $total packages to import"

    # Download packages into the repo directory (NOT extracting into /)
    local n=0
    while read -r repo filename; do
        [ -n "$filename" ] || continue
        n=$((n + 1))
        local got=0
        for m in $ARCH_MIRRORS; do
            if curl -kfSL --retry 2 --max-time 300 -o "$REPO_DIR/$filename" \
                    "$m/$repo/os/x86_64/$filename" 2>/dev/null && [ -s "$REPO_DIR/$filename" ]; then
                got=1
                break
            fi
        done
        [ "$got" -eq 1 ] || warn "  download failed: $repo/$filename"
        [ $((n % 20)) -eq 0 ] && log "    $n/$total done"
    done < "$work/dl.txt"
    log "  imported $n fcitx5 packages into pkgrepo"

    rm -rf "$work"
}
import_fcitx5 || warn "fcitx5 import failed (continuing)"

# =====================================================================
# Import X.Org Server + XFCE4 + curated tools into the packages repo.
#
# Previously the ISO baked this stack in via chroot/06-xorg-xfce.sh
# (extracted straight into /). That made the ISO ~500MB heavier and the
# desktop was permanently welded to the squashfs. Now the desktop is NOT
# part of the base system: boot lands on fbterm text consoles (Chinese
# terminals), and the user installs the GUI with `pacman -S xorg-server
# xfce4` from the Pages repo.
#
# We reuse arch-resolve.py (the same dependency-closure resolver the old
# ISO import used): it computes the closure of the X.Org+XFCE+curated seed
# set, treating everything LFS base already provides as satisfied, so
# Arch's glibc/gcc-libs/coreutils are NEVER pulled. Each package archive
# is downloaded as-is into the repo rather than extracted into /.
# =====================================================================
log '==> importing X.Org + XFCE + curated tools from Arch'
import_xfce() {
    local work="/tmp/xfce-import"
    rm -rf "$work"
    mkdir -p "$work/db"

    log "  downloading Arch repo databases"
    for repo in core extra; do
        local got=0
        for m in $ARCH_MIRRORS; do
            if curl -kfSL --retry 2 --max-time 120 -o "$work/db/$repo.db" \
                    "$m/$repo/os/x86_64/$repo.db" 2>/dev/null && [ -s "$work/db/$repo.db" ]; then
                got=1
                break
            fi
        done
        [ "$got" -eq 1 ] || { warn "Cannot download $repo.db — skipping X.Org/XFCE"; return 0; }
    done

    log "  resolving X.Org + XFCE + curated dependency closure"
    python3 "$SCRIPTS_DIR/chroot/arch-resolve.py" "$work/db" "$work" \
        > "$work/resolve.log" 2>&1 || {
        cat "$work/resolve.log" >&2
        warn "X.Org/XFCE resolver failed — skipping"
        return 0
    }
    cat "$work/summary.txt"
    grep '^WARN' "$work/resolve.log" || true

    local total
    total=$(wc -l < "$work/dl.txt")
    [ "$total" -gt 50 ] || { warn "X.Org/XFCE resolver produced unexpected closure ($total pkgs)"; return 0; }
    log "  X.Org/XFCE closure: $total packages to import"

    local n=0
    while read -r repo filename; do
        [ -n "$filename" ] || continue
        n=$((n + 1))
        local got=0
        for m in $ARCH_MIRRORS; do
            if curl -kfSL --retry 2 --max-time 300 -o "$REPO_DIR/$filename" \
                    "$m/$repo/os/x86_64/$filename" 2>/dev/null && [ -s "$REPO_DIR/$filename" ]; then
                got=1
                break
            fi
        done
        [ "$got" -eq 1 ] || warn "  download failed: $repo/$filename"
        [ $((n % 25)) -eq 0 ] && log "    $n/$total done"
    done < "$work/dl.txt"
    log "  imported $n X.Org/XFCE/curated packages into pkgrepo"

    rm -rf "$work"
}
import_xfce || warn "X.Org/XFCE import failed (continuing)"

# =====================================================================
# Package: Go toolchain (official binary distribution).
# Ships the full Go toolchain (go/gofmt + stdlib + pkg tool) to
# /usr/local/go, symlinked into /usr/local/bin. Same prebuilt pattern as
# the Rust/nodejs toolchains. Static-ish: depends on nothing in the repo.
# =====================================================================
log '==> building Go toolchain package'
build_go() {
    local tarball="$DL/go$GO_VER.linux-amd64.tar.gz"
    if [ ! -f "$tarball" ]; then
        warn "Go toolchain tarball not found: $tarball — skipping"
        return 0
    fi
    local stage="$STAGING/go-pkg"
    rm -rf "$stage"
    mkdir -p "$stage/usr/local"
    # tarball has top-level dir go/; extract into usr/local so we get
    # usr/local/go/<bin|pkg|src|...>
    tar xf "$tarball" -C "$stage/usr/local"

    [ -x "$stage/usr/local/go/bin/go" ] || { warn "Go binary missing after extract"; return 0; }

    # symlink the two main binaries into /usr/local/bin (PATH already covers it)
    mkdir -p "$stage/usr/local/bin"
    ln -sf /usr/local/go/bin/go "$stage/usr/local/bin/go"
    ln -sf /usr/local/go/bin/gofmt "$stage/usr/local/bin/gofmt"

    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = go
pkgver = $GO_VER-1
pkgdesc = Go programming language toolchain (official binary distribution)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = BSD-3-Clause
PKGEOF
    local archive="$REPO_DIR/go-$GO_VER-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage"
    log "  package: go-$GO_VER-1-x86_64.pkg.tar.zst"
}
build_go || warn "Go toolchain build failed (continuing)"

# =====================================================================
# Package: expat (runtime dep of the full-featured git package below;
# the ISO base system has no expat, so it ships as its own package)
# =====================================================================
log '==> building expat package'
build_expat() {
    local tarball="$DL/expat-$EXPAT_VER.tar.gz"
    if [ ! -f "$tarball" ]; then
        warn "expat tarball not found - skipping"
        return 0
    fi
    local src="$STAGING/expat-src"
    rm -rf "$src" && mkdir -p "$src"
    tar xf "$tarball" -C "$src" --strip-components=1

    local prefix="$STAGING/expat/prefix"
    rm -rf "$prefix" && mkdir -p "$prefix"
    (
        cd "$src"
        ./configure --prefix=/usr --disable-static \
            && make -j"$NPROC" \
            && make DESTDIR="$prefix" install
    ) > /tmp/expat-build.log 2>&1 || { warn "expat build failed"; return 0; }

    # runtime files only (drop docs/dev headers into the same package for
    # simplicity; they are tiny and enable building other software later)
    local stage="$STAGING/expat-pkg"
    rm -rf "$stage" && mkdir -p "$stage"
    cp -a "$prefix"/. "$stage/"
    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = expat
pkgver = ${EXPAT_VER}-1
pkgdesc = XML parsing library (dep of git-full)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = MIT
PKGEOF
    local archive="$REPO_DIR/expat-${EXPAT_VER}-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage" "$src"
    log "  package: expat-${EXPAT_VER}-1-x86_64.pkg.tar.zst"
}
build_expat || warn "expat build failed (continuing)"

# =====================================================================
# Package: git (FULL-featured). The ISO's bundled git was built with
# NO_CURL/NO_EXPAT (no https transport); this package provides https
# clone/push. pkgver carries -1 so it upgrades over the local 2.55.0.
# =====================================================================
log '==> building full-featured git package'
build_git_full() {
    local tarball="$DL/git-$GIT_VER.tar.xz"
    if [ ! -f "$tarball" ]; then
        warn "git tarball not found - skipping"
        return 0
    fi
    local src="$STAGING/git-src"
    rm -rf "$src" && mkdir -p "$src"
    tar xf "$tarball" -C "$src" --strip-components=1

    local prefix="$STAGING/git/prefix"
    rm -rf "$prefix" && mkdir -p "$prefix"
    (
        cd "$src"
        make prefix=/usr \
             NO_TCLTK=1 \
             NO_PYTHON=1 \
             NO_LIBPCRE2=1 \
             NO_NLS=1 \
             NO_GETTEXT=1 \
             NO_GPGME=1 \
             -j"$NPROC" all \
        && make prefix=/usr DESTDIR="$prefix" install
    ) > /tmp/git-build.log 2>&1 || { warn "full git build failed"; return 0; }

    local stage="$STAGING/git-pkg"
    rm -rf "$stage" && mkdir -p "$stage"
    cp -a "$prefix"/. "$stage/"
    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = git
pkgver = ${GIT_VER}-1
pkgdesc = git - distributed version control system (https/ssh transport enabled)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = GPL-2.0-only
depends = curl
depends = expat
depends = openssh
PKGEOF
    local archive="$REPO_DIR/git-${GIT_VER}-1-x86_64.pkg.tar.zst"
    ( cd "$stage" && tar --zstd -cf "$archive" .PKGINFO . )
    rm -rf "$stage" "$src"
    log "  package: git-${GIT_VER}-1-x86_64.pkg.tar.zst"
}
build_git_full || warn "full git build failed (continuing)"

# =====================================================================
# Package: astroterm (terminal planetarium; prebuilt STATIC binary from
# the upstream release asset - same pattern as fd/rg/bat. Static means
# NO depends entries: nothing in this repo would satisfy them anyway.)
# =====================================================================
log '==> building astroterm package'
build_astroterm() {
    local bin="$DL/astroterm-linux-x86_64"
    if [ ! -f "$bin" ]; then
        warn "astroterm binary not found - skipping"
        return 0
    fi
    local stage="$STAGING/astroterm-pkg"
    rm -rf "$stage" && mkdir -p "$stage/usr/bin"
    install -m 755 "$bin" "$stage/usr/bin/astroterm"
    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = astroterm
pkgver = ${ASTROTERM_VER#v}-1
pkgdesc = A planetarium for your terminal (prebuilt static)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = MIT
PKGEOF
    local archive="$REPO_DIR/astroterm-${ASTROTERM_VER#v}-1-x86_64.pkg.tar.zst"
    ( cd "$stage" && tar --zstd -cf "$archive" .PKGINFO . )
    rm -rf "$stage"
    log "  package: astroterm-${ASTROTERM_VER#v}-1-x86_64.pkg.tar.zst"
}
build_astroterm || warn "astroterm build failed (continuing)"

# =====================================================================
# Package: typst (typesetting system; prebuilt STATIC musl binary -
# same pattern as fd/rg/bat/astroterm, empty depends)
# =====================================================================
log '==> building typst package'
build_typst() {
    local tarball="$DL/typst-x86_64-unknown-linux-musl.tar.xz"
    if [ ! -f "$tarball" ]; then
        warn "typst tarball not found - skipping"
        return 0
    fi
    local stage="$STAGING/typst-pkg"
    rm -rf "$stage" && mkdir -p "$stage/usr/bin"
    tar xf "$tarball" -C "$stage/usr/bin" --strip-components=1 \
        typst-x86_64-unknown-linux-musl/typst \
        || { warn "typst extract failed"; return 0; }
    chmod 755 "$stage/usr/bin/typst"
    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = typst
pkgver = ${TYPST_VER#v}-1
pkgdesc = Typst - composable typesetting system (prebuilt static musl)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = Apache-2.0
PKGEOF
    local archive="$REPO_DIR/typst-${TYPST_VER#v}-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage"
    log "  package: typst-${TYPST_VER#v}-1-x86_64.pkg.tar.zst"
}
build_typst || warn "typst build failed (continuing)"

# =====================================================================
# Package: tdf (TUI PDF viewer; Rust source build. mupdf-rs vendors the
# C library, so only /opt/rust + gcc are needed. Git-based cargo deps
# require the CA env - /etc/environment is NOT read in this env -i
# shell, so export SSL_CERT_FILE explicitly.)
# =====================================================================
log '==> building tdf package (cargo, this takes a while)'
build_tdf() {
    local tarball="$DL/tdf-$TDF_VER.tar.gz"
    if [ ! -f "$tarball" ]; then
        warn "tdf tarball not found - skipping"
        return 0
    fi
    if [ ! -x /opt/rust/bin/cargo ]; then
        warn "/opt/rust/bin/cargo missing - skipping tdf"
        return 0
    fi
    local src="$STAGING/tdf-src"
    rm -rf "$src" && mkdir -p "$src"
    tar xf "$tarball" -C "$src" --strip-components=1

    export PATH="/opt/rust/bin:$PATH"
    export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
    (
        cd "$src"
        cargo build --release
    ) > /tmp/tdf-build.log 2>&1 || {
        warn "tdf cargo build failed (see /tmp/tdf-build.log in chroot)"
        return 0
    }

    local stage="$STAGING/tdf-pkg"
    rm -rf "$stage" && mkdir -p "$stage/usr/bin"
    install -m 755 "$src/target/release/tdf" "$stage/usr/bin/tdf" \
        || { warn "tdf binary missing"; return 0; }
    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = tdf
pkgver = ${TDF_VER#v}-1
pkgdesc = Terminal PDF viewer (TUI, mupdf rendering)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = AGPL-3.0-only
PKGEOF
    local archive="$REPO_DIR/tdf-${TDF_VER#v}-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage" "$src"
    log "  package: tdf-${TDF_VER#v}-1-x86_64.pkg.tar.zst"
}
build_tdf || warn "tdf build failed (continuing)"

# =====================================================================
# Packages: libevent + tmux. tmux's only external dep; ncurses comes
# from LFS but is NOT registered in pacman, so tmux declares only
# libevent (which IS a repo package).
# =====================================================================
log '==> building libevent + tmux packages'
build_libevent() {
    local tarball="$DL/libevent-$LIBEVENT_VER.tar.gz"
    if [ ! -f "$tarball" ]; then
        warn "libevent tarball not found - skipping"
        return 0
    fi
    local src="$STAGING/libevent-src"
    rm -rf "$src" && mkdir -p "$src"
    tar xf "$tarball" -C "$src" --strip-components=1

    local prefix="$STAGING/libevent/prefix"
    rm -rf "$prefix" && mkdir -p "$prefix"
    (
        cd "$src"
        ./configure --prefix=/usr --disable-static \
            && make -j"$NPROC" \
            && make DESTDIR="$prefix" install
    ) > /tmp/libevent-build.log 2>&1 || { warn "libevent build failed"; return 0; }

    local stage="$STAGING/libevent-pkg"
    rm -rf "$stage" && mkdir -p "$stage"
    cp -a "$prefix"/. "$stage/"
    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = libevent
pkgver = ${LIBEVENT_VER#release-}-1
pkgdesc = Event notification library (dep of tmux)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = BSD-3-Clause
PKGEOF
    local archive="$REPO_DIR/libevent-${LIBEVENT_VER#release-}-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage" "$src"
    log "  package: libevent-${LIBEVENT_VER#release-}-1-x86_64.pkg.tar.zst"
}
build_libevent || warn "libevent build failed (continuing)"

build_tmux() {
    local tarball="$DL/tmux-$TMUX_VER.tar.gz"
    if [ ! -f "$tarball" ]; then
        warn "tmux tarball not found - skipping"
        return 0
    fi
    local src="$STAGING/tmux-src"
    rm -rf "$src" && mkdir -p "$src"
    tar xf "$tarball" -C "$src" --strip-components=1

    local evp="$STAGING/libevent/prefix"
    if [ ! -d "$evp" ]; then
        warn "libevent staging missing - skipping tmux"
        return 0
    fi
    local prefix="$STAGING/tmux/prefix"
    rm -rf "$prefix" && mkdir -p "$prefix"
    (
        cd "$src"
        PKG_CONFIG_PATH="$evp/usr/lib/pkgconfig" \
        CPPFLAGS="-I$evp/usr/include" \
        LDFLAGS="-L$evp/usr/lib" \
        ./configure --prefix=/usr \
            && make -j"$NPROC" \
            && make DESTDIR="$prefix" install
    ) > /tmp/tmux-build.log 2>&1 || { warn "tmux build failed"; return 0; }

    local stage="$STAGING/tmux-pkg"
    rm -rf "$stage" && mkdir -p "$stage"
    cp -a "$prefix"/. "$stage/"
    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = tmux
pkgver = ${TMUX_VER}-1
pkgdesc = Terminal multiplexer
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = ISC
depends = libevent
PKGEOF
    local archive="$REPO_DIR/tmux-${TMUX_VER}-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage" "$src" "$STAGING/libevent"
    log "  package: tmux-${TMUX_VER}-1-x86_64.pkg.tar.zst"
}
build_tmux || warn "tmux build failed (continuing)"

# =====================================================================
# Package: ddd (GNU Data Display Debugger). Removed from Arch repos and
# needs Motif - pull the Debian amd64 debs (ddd + libmotif) at build
# time, merging the binary + libXm into ONE self-contained package so
# no unresolvable depends are declared. X11 libs come from the ISO's
# Xorg import; if a runtime lib is missing (e.g. libXp) extend here.
# =====================================================================
log '==> building ddd package (Debian deb extraction)'
build_ddd() {
    fetch_latest_deb() {
        local dir="$1" prefix="$2" out="$3" idx f
        idx=$(curl -kfSL --max-time 60 "https://deb.debian.org/debian/pool/main/$dir/" 2>/dev/null) || return 1
        f=$(printf '%s' "$idx" | grep -o "href=\"[^\"]*${prefix}[^\"]*_amd64.deb\"" | tail -1 | cut -d'"' -f2)
        [ -n "$f" ] || return 1
        curl -kfSL --retry 2 --max-time 300 -o "$out" "https://deb.debian.org/debian/pool/main/$dir/$f" || return 1
        printf '%s' "$f"
    }
    local ddd_deb="/tmp/ddd.deb" motif_deb="/tmp/libmotif.deb" ddd_fname
    ddd_fname=$(fetch_latest_deb "d/ddd" "ddd_" "$ddd_deb") \
        || { warn "ddd deb not found in Debian pool - skipping"; return 0; }
    fetch_latest_deb "m/motif" "libmotif" "$motif_deb" \
        || { warn "libmotif deb not found - skipping ddd"; return 0; }
    local ddd_ver="${ddd_fname#ddd_}"; ddd_ver="${ddd_ver%%_amd64.deb}"

    local stage="$STAGING/ddd-pkg"
    rm -rf "$stage" && mkdir -p "$stage"
    local tmpx="/tmp/ddd-extract"
    rm -rf "$tmpx" && mkdir -p "$tmpx"
    ar p "$ddd_deb" data.tar.xz | tar xJ -C "$tmpx" 2>/dev/null \
        || ar p "$ddd_deb" data.tar.zst | tar --zstd -xf - -C "$tmpx" \
        || { warn "ddd deb extract failed"; return 0; }
    cp -a "$tmpx/usr" "$stage/" 2>/dev/null
    rm -rf "$tmpx" && mkdir -p "$tmpx"
    ar p "$motif_deb" data.tar.xz | tar xJ -C "$tmpx" 2>/dev/null \
        || ar p "$motif_deb" data.tar.zst | tar --zstd -xf - -C "$tmpx" \
        || { warn "libmotif deb extract failed"; return 0; }
    mkdir -p "$stage/usr/lib"
    if [ -d "$tmpx/usr/lib/x86_64-linux-gnu" ]; then
        cp -a "$tmpx/usr/lib/x86_64-linux-gnu"/. "$stage/usr/lib/"
    fi
    [ -d "$tmpx/usr/lib" ] && cp -a "$tmpx/usr/lib"/. "$stage/usr/lib/" 2>/dev/null
    rm -rf "$tmpx"
    [ -e "$stage/usr/bin/ddd" ] || { warn "ddd binary missing after extract"; return 0; }

    cat > "$stage/.PKGINFO" << PKGEOF
pkgname = ddd
pkgver = ${ddd_ver%-*}-1
pkgdesc = GNU Data Display Debugger (Motif GUI; libXm bundled)
arch = x86_64
builddate = $(date +%s)
packager = LFS-CN Build System <lfs-cn@build>
license = GPL-3.0-only
PKGEOF
    local archive="$REPO_DIR/ddd-${ddd_ver%-*}-1-x86_64.pkg.tar.zst"
    (
        cd "$stage"
        : > "/tmp/pkgfiles.$$"
        printf '%s\0' .PKGINFO >> "/tmp/pkgfiles.$$"
        find . -mindepth 1 ! -path './.PKGINFO' -printf '%P\0' >> "/tmp/pkgfiles.$$"
        tar --zstd --null --no-recursion -T "/tmp/pkgfiles.$$" -cf "$archive"
        rm -f "/tmp/pkgfiles.$$"
    )
    rm -rf "$stage"
    log "  package: ddd-${ddd_ver%-*}-1-x86_64.pkg.tar.zst"
}
build_ddd || warn "ddd build failed (continuing)"

# =====================================================================
# lfs-base shim into the repo (built & registered locally by 05-extras;
# the tarball rides in $DL). Imported Arch packages depend on glibc etc.
# - without this shim in the repo, fresh dependency resolution against
# the Pages repo alone could never succeed.
# =====================================================================
shim_tarball="$DL/lfs-base-13.0-1-x86_64.pkg.tar.zst"
if [ -f "$shim_tarball" ]; then
    cp -v "$shim_tarball" "$REPO_DIR/"
else
    warn "lfs-base shim tarball missing - imported packages may not be installable"
fi

# =====================================================================
# Sanitize Arch epoch filenames: upload-artifact rejects ':' (NTFS-
# incompatible); rename before repo-add so %FILENAME% in the db
# matches the on-disk name.  repo-add uses basename "${1##*/}".
# =====================================================================
log '==> sanitizing epoch colons in filenames'
cd "$REPO_DIR"
for f in *:*; do
    [ -e "$f" ] || continue
    safe="${f//:/_}"
    mv -v "$f" "$safe"
done

# =====================================================================
# Generate pacman repository database
# =====================================================================
log '==> generating pacman repository database'
cd "$REPO_DIR"

# Collect all .pkg.tar.zst files (including any from Arch import)
pkg_files=(*.pkg.tar.zst)
if [ -e "${pkg_files[0]}" ]; then
    repo-add lfscn.db.tar.gz "${pkg_files[@]}" || {
        warn "repo-add failed, retrying verbose"
        repo-add lfscn.db.tar.gz "${pkg_files[@]}"
    }
    ln -sfv lfscn.db.tar.gz lfscn.db
    log "  lfscn.db created with ${#pkg_files[@]} packages"
else
    warn "no packages found in $REPO_DIR"
fi

# =====================================================================
# Summary
# =====================================================================
log '==> package repo contents:'
ls -lh "$REPO_DIR"/ 2>/dev/null || true
log '==> packages build complete'
